model_name: null
tf_config:
  recompute_granularity: full
  recompute_method: uniform
  recompute_num_layers: 1
pp_size: 1
cp_size: 1
tp_size: 1
ep_size: 1
etp_size: null
max_length_per_device: null
optimizer:
  lr: 5e-6
  min_lr: 5e-7
  weight_decay: 1e-2
  clip_grad: 1.0
scheduler:
  init_lr: ${critic.optimizer.min_lr}
  lr_decay_style: constant
  warmup_ratio: 0.1
  start_wd: ${critic.optimizer.weight_decay}
  end_wd: ${critic.optimizer.weight_decay}
  wd_incr_style: constant
offload_optimizer: true
use_lora: false
lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  use_rslora: false
  target_modules:
    - q_proj
    - v_proj
    - k_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
  modules_to_save: null