model_name: null
use_liger_kernel: false
enable_gradient_checkpointing: true
ddp_size: 1
tp_size: 1
cp_size: 1
max_length_per_device: null
optimizer:
  lr: 1e-6
  weight_decay: 1e-2
max_grad_norm: 1.0
scheduler:
  name: constant
  warmup_ratio: 0.1
offload_optimizer: true
use_lora: false
lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  use_rslora: false
  target_modules:
    - q_proj
    - v_proj
    - k_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
  modules_to_save: null